ALTER TABLE `Product` ADD COLUMN `gstRate` DECIMAL(5, 2) NOT NULL DEFAULT 0;

ALTER TABLE `CartItem`
  ADD COLUMN `gstRate` DECIMAL(5, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `gstAmount` DECIMAL(10, 2) NOT NULL DEFAULT 0;

ALTER TABLE `Order`
  ADD COLUMN `totalGst` DECIMAL(10, 2) NOT NULL DEFAULT 0;

ALTER TABLE `OrderItem`
  ADD COLUMN `gstRate` DECIMAL(5, 2) NOT NULL DEFAULT 0,
  ADD COLUMN `gstAmount` DECIMAL(10, 2) NOT NULL DEFAULT 0;
