ALTER TABLE `ServiceBooking`
  MODIFY `status` ENUM('PENDING', 'ACCEPTED', 'EN_ROUTE', 'IN_PROGRESS', 'REVISIT_REQUESTED', 'COMPLETED', 'CANCELLED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
  ADD COLUMN `revisitReason` TEXT NULL,
  ADD COLUMN `revisitRequestedAt` DATETIME(3) NULL,
  ADD COLUMN `revisitAcceptedAt` DATETIME(3) NULL;
